# docker-compose run --rm --service-ports python bash
# the above command will start a container for this one-off python-django development env in a bash shell
# django-admin.py startproject eshop . , run this command in the bash to create a django project skeleton
# environment variables is defined in .env file or the local env
# docker-compose up -d, to start the server
version: "3"
services:
  python:
    image: "liuchen/python_eshop"
    env_file:
      # ESHOP_ENV is the env var in local shell, the value will be dev, uat or pro
      # $(ESHOP_ENV).env is the file which defined all env vars for the container
      - ./envfiles/${ESHOP_ENV}.env
    volumes:
      - "/var:/var"
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
networks:
  default:
    external:
      # make sure the external network is created in advance using below command
      # docker network create --driver bridge development
      name: development
