# This is the base compose file for all containers
# docker-compose run --rm --service-ports python bash
# the above command will start a container for this one-off python-django development env in a bash shell
# django-admin.py startproject eshop . , run this command in the bash to create a django project skeleton
# environment variables is defined in .env file or the local env
# docker-compose up -d, to start the server

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: eshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eshop
  template:
    metadata:
      labels:
        app: eshop
    spec:
      containers:
        - name: eshop-container
          image: liuchen/python_eshop
          env:
          - name: ESHOP_ENV
            value: "pro"
          - name: ESHOP_DATABASE_NAME
            value: "eshop"
          - name: ESHOP_DATABASE_USER
            value: "postgres"
          - name: ESHOP_DATABASE_PASSWORD
            value: "liuchen"
          - name: ESHOP_DATABASE_HOST
            value: "eshop"
          - name: ESHOP_DATABASE_PORT
            value: "5432"
          command: ["python"]
          args: ["manage.py", "runserver", "0.0.0.0:8000"]
          ports:
          - containerPort: 80
